### ISSUE TITLE
How to obtain Scaler?

### ISSUE THREAD

**Issue by viethungluu** [vladan-stojnic/CMC-remote-sensing#1]
Hi, thank you for this repo. I would like to ask if what is the function of Scaler and how to build it (as I can not find information about it on the paper or code)

**Comment by vladan-stojnic** [comment]
Hi, sorry about that. Scaler is sklearn's standard scaler (scaling to zero mean and unit variance). We train it the same way we calculate PCA decomposition. We randomly sample 144 pixel values from each of 200k training images from BigEarthNet, and we learn mean and variance for all  channels. 

We do this because channels of multispectral images have big differences in ranges of values, which could create a problem for training of a CNN. But more importantly this is needed to be done before calculating PCA because different scales of values would significantly impact PCA decomposition.
